const URL_PATHS = {
    LOGIN: "api/auth/login-admin",
    LOG_OUT: "api/auth/logout",
    REGISTER: "api/auth/register",
    GET_CURRENT_USER: "api/users/get-current-user",
    CREATE_USER: "api/users",
    GET_USER: "api/users/get-list",
    DETAIL_USER: "api/users/detail",
    RESOURCE_ACTION: "api/role/resource-actions",
    ROLE_GET_DETAIL: "api/role/get-detail",
    ROLE_GET: "api/role",
    ROLE_EDIT: "api/role/edit-role",
    GET_BOOKING: "api/booking/get-list",
    GET_DOCTOR: "api/users/get-list-doctor",
    GET_LIST_MAIN_SERVICE: "api/main-service/getAll",
    GET_LIST_TIME_TYPE: "api/time-type/get-list",
    CREATE_BOOKING: "api/booking/create",
    DETAIL_BOOKING: "api/booking/detail-booking",
    CONFIRM_BOOKING: "api/booking/update-status",
}
export default URL_PATHS